version: '3'

services:
  web:
    build: ./
    volumes:
      - .:/usr/src/app
    ports:
      - 5002:3000
    environment:
      PASSWORD_FOR_POSTGRES: 'mysecretpassword'
    depends_on:
      - db
  db:
    image: postgres:9
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'mysecretpassword'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data



